services:
  - type: web
    name: votingportal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      sh -c 'alembic upgrade head && 
      uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: voting_db
          property: connectionString

databases:
  - name: voting_db
    databaseName: voting_db
    plan: free