services:
  - type: web
    name: votingportal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health
    autoDeploy: false
    numInstances: 1

databases:
  - name: voting_db
    databaseName: voting_db
    plan: free